### ISSUE TITLE
Use an alternate testing tool?

### ISSUE THREAD

**Issue by ayan-usgs** [USGS-CIDA/MLR-Ddot-Ingester#1]
I have some hesitance about using nose as specified here: https://github.com/USGS-CIDA/MLR-Ddot-Ingester/blob/b865d5d13007dc7f6938d6baef6169247accfd9a/test_requirements.txt#L2
and
https://github.com/USGS-CIDA/MLR-Ddot-Ingester/blob/b865d5d13007dc7f6938d6baef6169247accfd9a/requirements.txt#L9

This can be found on the nose documentation: 
> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

**Comment by mbucknell** [comment]
It shouldn't be in requirements.txt. I'll investigate Nose2 and py.test. The nice thing about nosetest is you can get code coverage metrics. Hopefully, I can find something that provides that.

**Comment by mbucknell** [comment]
Decided to go with super simple and just use unittest without any test runner. I can still use coverage for code statistics which I have done in travis. I'm not getting the code stats that I want on the Coveralls dashboard. See https://github.com/USGS-CIDA/MLR-Ddot-Ingester/pull/3
