### ISSUE TITLE
__str__ and __repr__ for ParseError

### ISSUE THREAD

**Issue by ayan-usgs** [USGS-CIDA/MLR-Ddot-Ingester#2]
Would it be useful to include to `__str__` and `__repr__` methods for the `ParseError` exeception? https://github.com/USGS-CIDA/MLR-Ddot-Ingester/blob/b865d5d13007dc7f6938d6baef6169247accfd9a/ddot_utils.py#L65-L67

Just wondering if that's useful stuff to have in the logs when exceptions occurs.

**Comment by mbucknell** [comment]
Good catch! I'll add those.
